---
title: "Residue Example"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Residue Example}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(kraken)
library(dplyr)
library(tidyr)
library(ggplot2)
library(drc)
library(ggstar)
library(knitr)
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(error = FALSE)
```

## Data

Data exported from fish farm database as .csv file. Saved locally and use the
'Import Dataset' tool in the Environment pane to import data or use `read.csv()`
function and paste in file path - but replace  '\' with '/' in the path.

```{r data}
# data <- read.csv(system.file("extdat/test-data/", "residue-test-data.csv", package = "kraken"))

 data <- read.csv("C:/Users/Tim.Foster/OneDrive - Scottish Environment Protection Agency/DNA Data/Readiness Data/ellipse-area/survey-5326-demo.csv")
data <- data[data$Transect != 1, ]


# data <- read.csv("C:/Users/Tim.Foster/OneDrive - Scottish Environment Protection Agency/DNA Data/Readiness Data/ellipse-area/survey-5379.csv")
# data <- read.csv("C:/Users/Tim.Foster/OneDrive - Scottish Environment Protection Agency/DNA Data/Readiness Data/ellipse-area/survey-5379-2026-04-14.csv")

# data <- read.csv("C:/Users/Tim.Foster/OneDrive - Scottish Environment Protection Agency/DNA Data/Readiness Data/ellipse-area/rum1.csv")


# Filter data for my particular farm/date of interest
# data <- dplyr::filter(data, Site.ID == "FFMC27")

# Select only the columns needed for calculations
data <- dplyr::select(data,
  EQS..ng.kg.,
  "Survey_date" = Survey.Date,
  "MCFF" = Site.ID,
  Transect,
  "Station" = Station.Order..transect.,
  Easting,
  Northing,
  "Embz-1" = EmBz.residues..Rep.1...ng.kg.,
  "Embz-2" = EmBz.residues..Rep.2..ng.kg.,
  "Embz-3" = EmBz.residues..Rep.3..ng.kg.
)

# Pivot the data into structure require for calculations
data <- tidyr::pivot_longer(
  data,
  cols = c("Embz-1",
           "Embz-2",
           "Embz-3"),
  names_to = "Station_id", values_to = "IQI"
)

data$IQI <- as.numeric(data$IQI)
pass_fail <- unique(na.omit(data$EQS..ng.kg.))
```


## Calculate

Run data through calculations.

```{r run-kraken, fig.height=0.1, fig.width=0.1}
output <- kraken::kraken(data,
  pass_fail = pass_fail,
  method = "residue",
#  loess = FALSE,
#  n_try = 10,
#   , 
   ellipse_representative = TRUE
)
```

## Map

```{r map, fig.width=5}
map <- output$object[output$question == "map"]
map[[1]]
```


# Model Info


```{r model}
model <- output$object[output$question == "model_info"][[1]]

knitr::kable(model)

warnings <- output$response[grepl( "_warning", output$question)]

knitr::kable(warnings, col.names = "Warnings")



```

## Plots

```{r plots, fig.width=5}


# pivot output
# plots_data <- output %>% dplyr::filter(grepl("FFMC27", location_id))
plots_data <- output %>% 
  dplyr::filter(question %in% c("Distance", "IQI", "MCFF_Transect"))
plots_data <- distinct(plots_data)

# plots_data <- pivot_wider(plots_data, names_from = question,
#                           values_from = response)
# plots_data$IQI <- as.numeric(plots_data$IQI)
# plots_data$Distance <- as.numeric(plots_data$Distance)


plots_data <- purrr::map_df(
  split(plots_data, plots_data$sample_id), function(sample) {

  distance <- filter(sample, question == "Distance")
  MCFF <- filter(sample, question == "MCFF_Transect")
  if(length(sample$response[sample$question == "IQI"]) == 3) { 
  sample <- bind_rows(sample, distance, distance, MCFF, MCFF)
  sample <- arrange(sample, question)
  sample$ID <- rep(1:3,3 )
  }
  if(length(sample$response[sample$question == "IQI"]) == 2) { 
  sample <- bind_rows(sample, distance, MCFF)
  sample <- arrange(sample, question)
  sample$ID <- rep(1:2,3 )
  }

  sample <- pivot_wider(sample, names_from = question, 
                          values_from = response)
sample$IQI <- as.numeric(sample$IQI)
sample$Distance <- as.numeric(sample$Distance)
  
  return(sample)
})

hex_df <- bind_rows(output$object[output$question == "hex_df"])
hex_df$Distance <- as.numeric(hex_df$Distance)
hex_df$IQI <- as.numeric(hex_df$IQI)
hex_df$Transect <- as.numeric(hex_df$Transect)
hex_df$Counts <- as.numeric(hex_df$Counts)
hex_df$shape <- NA
hex_df$size <- NA
hex_df$colour <- NA
hex_df$shape[hex_df$Source == "Prob. model"] <- "hexagon"
hex_df$shape[hex_df$Source == "Survey data"] <- "circle"
hex_df$size[hex_df$Source == "Prob. model"] <- 3
hex_df$size[hex_df$Source == "Survey data"] <- 2


breach_ensemble <- bind_rows(output$object[output$question == "breachPositionEnsemble"])
breach_ensemble <- breach_ensemble %>%
  dplyr::select(Transect, `breachDistance_95thPercentile`) %>% 
  distinct()



p <- list()
for(i in model$Transect[1]:max(model$Transect)) {
  model_plot <- model[model$Transect == i, ]
  plot_data <- plots_data[grepl(paste0("- ",i), plots_data$MCFF_Transect), ]
  model_type <- paste0(trimws(substr(model_plot$bestModel,1,4)), "()")
  message(model_type)
  transect_hex <- hex_df[hex_df$Transect == i, ]

  if(model_type %in% c("Insu()","Regr()")) {
  p[[i]] <- ggplot(aes(Distance, IQI), data = plot_data) +
  geom_point() +
  ylab("Emamectin (ng/kg)") +
  ggplot2::ggtitle(paste0("Site: ", unique(plot_data$project_id)),
                       subtitle = paste0(unique(plot_data$MCFF_Transect),
                                         " Model fit not of sufficient quality to use")) +
  geom_hline(yintercept = pass_fail, colour = "black", linetype = 2) 
    } 
  if(!model_type %in% c("Insu()","Regr()")){
  p[[i]] <- ggplot(aes(Distance, IQI), data = plot_data) +
  geom_point() +
  geom_smooth(method = drm,
              method.args = list(fct = eval(parse(text=model_type))),
              se = FALSE) +
  ylab("Emamectin (ng/kg)") +
  xlab("Distance (m)") +
  ggtitle(paste0("Transect: ",  unique(plot_data$MCFF_Transect))) +
  geom_hline(yintercept = pass_fail, colour = "black", linetype = 2) 

  } 
}


for(i in model$Transect[1]:max(model$Transect)) {
  model_plot <- model[model$Transect == i, ]
  plot_data <- plots_data[grepl(paste0("- ",i), plots_data$MCFF_Transect), ]
  model_type <- paste0(trimws(substr(model_plot$bestModel,1,4)), "()")
  message(model_type)
  transect_hex <- hex_df[hex_df$Transect == i, ]
    breach <- breach_ensemble[breach_ensemble$Transect == i, ]
  if(!model_type %in% c("Insu()","Regr()")){
  p[[i]] <- ggplot(aes(
    Distance,
  IQI, 
  colour = Counts / 10, fill = Counts / 10),
  data = transect_hex) +
  geom_star(
  starshape = transect_hex$shape,  size = transect_hex$size) +
  ylab("Emamectin (ng/kg)") +
  xlab("Distance (m)") +
  ggtitle(paste0("Transect: ",  unique(plot_data$MCFF_Transect))) +
  geom_hline(yintercept = pass_fail, colour = "black", linewidth = 1, linetype = 2) +
  geom_vline(xintercept = breach$breachDistance_95thPercentile,
            colour = "blue", 
            linetype = 2,
            linewidth = 1) +
    scale_colour_continuous(palette = c("#FEE0D2", "#FC9272", "#DE2D26")) +
 scale_fill_continuous(palette = c("#FEE0D2", "#FC9272", "#DE2D26")) +
   labs(fill="Model fits", colour = "Model fits")
  } 
}


p[2][[1]]
p[3][[1]]
p[4][[1]]

```

```{r}

knitr::kable(breach_ensemble)
```



```{r, eval=FALSE}

output$response[output$question == "area_95_confidence"]

(100/ 196238 )  * 327687.555651631

(100/ 177068 )  * 108298

```


